name: Discord PR Notification

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
    - name: Send PR Notification to Discord
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: "A new pull request is ready for review: ${{ github.event.pull_request.html_url }}"
